"""Integrators constants"""
TOKEN_ERROR_MESSAGE = 'Token error'
API_VERSION_CALL = "/api/v1/"
API_ADOM_CALL_NAME = "adom"
API_CALL_FORTIVIEW_NAME = "fortiview"
API_CALL_MANAGER = "manager"
API_CALL_EVENTMGMT_NAME = "eventmgmt"
API_CALL_REPORTS_NAME = "reports"
API_CALL_LOGVIEW_NAME="logview"
API_CALL_LOGSEARCH_NAME="logsearch"
TRAFFIC_LOGTYPE = "traffic"
LINK_QUALITY_LOGVIEW = "event"
API_SD_WAN_SLA_LOG_CALL_NAME = "sd-wan-sla-log"
API_SD_WAN_INTERFACE_LOG_CALL_NAME = "sd-wan-intf-log"
API_CALL_REPORTS = "reports"
