import os
import uuid


# -------------- Unit Test Constants -------------
FORTINET_MANAGER_BASE_URL = os.environ.get("FORTINET_MANAGER_BASE_URL")
FORTINET_MANAGER_CREDENTIAL_UUID = os.environ.get("FORTINET_MANAGER_CREDENTIAL_UUID")
EXPECTED_SUCCESS_STATUS = '200 OK'
EXPECTED_BAD_REQUEST_STATUS = '400 BAD REQUEST'
EXPECTED_INTERNAL_SERVER_ERROR_STATUS = '500 INTERNAL SERVER ERROR'
ERROR_MESSAGE_INTERNAL_SERVER_ERROR = 'Internal server error'
ERROR_MESSAGE_REQUEST_FAIL = "API request error"
EXPECTED_BAD_ERROR = "'NoneType' object does not support item assignment"
EXPECTED_BAD_VALUE_ERROR = "ValueError"
EXPECTED_BAD_KEY_ERROR = "KeyError"
EXPECTED_BAD_NAME_ERROR = "NameError"
EXPECTED_BAD_ATTRIBUTE_ERROR = 'AttributeError'
EXPECTED_VALIDATION_EXCEPTION = "ValidationException"
EXPECTED_HOSTRESPONDEDWITHERROR_EXCEPTION = "HostRespondedWithErrorException"
EXPECTED_HOSTNOTREACHABLE_EXCEPTION = "HostNotReachableException"
EXPECTED_TOKENCREATION_EXCEPTION = "TokenCreationException"
UNIT_TEST_ADOM_NAME = "CloudSmartz"
UNIT_TEST_BAD_ADOM_NAME = "bas adom name"
UNIT_TEST_DEVICE_ID = "CS-TX-101F"
UNIT_TEST_BAD_DEVICE_ID = "BAD-DEVICE-ID"
UNIT_TEST_CORRELATION_ID = str(uuid.uuid4())
UNIT_TEST_CREDENTIAL_ID = '22'
UNIT_TEST_METRIC_NAME = 'policy-hits'
UNIT_TEST_BAD_METRIC_NAME = 'policy-hit'
UNIT_TEST_BANDWIDTH_RATE = 'bandwidth-rate'
UNIT_TEST_TRAFFIC_SUMMARY = 'traffic-summary'
UNIT_TEST_SITE_DETAILS = 'site-details'
UNIT_TEST_TOP_APPLICATION_USAGE = 'top-application-usage'
UNIT_TEST_RISK_ANALYSIS = 'risk-analysis'
UNIT_TEST_TOP_USERS = 'top-users'
UNIT_TEST_INVALID_MATRIC_NAME_TOP_APPLICATION_USAGE = 'top-application-usageS'
UNIT_TEST_TOP_APPLICATION_THREATS = 'top-threats'
UNIT_TEST_SD_WAN_USAGES = 'sd-wan-usage'
UNIT_TEST_SITE_MAP ='site-map'
UNIT_TEST_ERROR_CODE = 9003
API_VERSION_CALL = "/api/v1/"
API_ADOM_CALL_NAME = "adom"
API_ADOM_CALL_BAD_NAME = "bad adom"
API_CALL_FORTIVIEW_NAME = "fortiview"
DEVICE_SERIAL_NUMBER = 'FGT60FTK19034698'
TIMEOUT_PERIOD = 3600
SUCCESS_CODE = 200
ERROR_CODE_BAD_REQUEST = 400
ERROR_CODE_UNAUTHORIZED_ACCESS = 401
ERROR_CODE_INTERNAL_SERVER_ERROR = 500
EPOCH_TO_DATETIME_FORMAT = "%Y-%m-%d %H:%M"
INPUT_PAYLOAD_MIN_LIMIT = 1
INPUT_PAYLOAD_MAX_LIMIT = 500
PROVIDE_VALID_FILTER_OPTION = "Please provide a valid option for filter"
PROVIDE_VALID_LIMIT_TYPE = "Please provide a proper number for limit"
PROVIDE_VALID_TIME_RANGE_TYPE = "Please provide a valid time range object"
PROVIDE_START_AND_END_TIME = "Please provide both start and end time"
PROVIDE_START_TIME = "Please provide start time"
PROVIDE_END_TIME = "Please provide end time"
PROVIDE_SAME_DATE_FORMATS = 'Please ensure that the date formats for the dates provided are the same'
PROVIDE_VALID_RANGE = 'Please check the range of your dates provided'
PROVIDE_TIME_RANGE = "Please provide a time range"
PROVIDE_VALID_DEVICE = "Please provide a valid option for device"
PROVIDE_VALID_SORT_BY = "Please provide a valid option for sort by"
PROVIDE_SORT_BY = "Please provide sort by"
PROVIDE_FIELD_AND_ORDER_SORT_BY = "Please provide both field and order"
PROVIDE_VALID_SORT_BY_OPTION_FOR_END_POINT = "The value provided for sort by in %s is not proper for this end point"
PROVIDE_LIMIT_IN_PROPER_RANGE = "Please provide a limit that is between {} and {} "
PROVIDE_PROPER_DATE_FORMAT = "incorrect date string format provided. It should be yyyy-MM-ddTHH:mm:ssZ or yyyy-MM-dd HH:mm:ss"
PROVIDE_VALID_METRIC_NAME = "Invalid metric name"
PROVIDE_VALID_START_DATE_EPOCH = 'Invalid start_date must be epoch timestamp'
PROVIDE_START_DATE = 'Please provide start date'
PROVIDE_VALID_END_DATE_EPOCH = 'Invalid end_date must be epoch timestamp'
PROVIDE_END_DATE = 'Please provide end date'
VALIDATE_TOKEN_SUCCESS_TEXT = "Valid Token"
SUCCESSFULLY_GENERATED_TOKEN = '1a2b3c'
HOST_NOT_REACHABLE = 'Host Not Reachable'
FORTINET_ANALYZER_NOT_REACHABLE = 'Fortinet Analyzer is not reachable'
BAD_ADOM_NAME_RESPONSE_CODE = 9007
IMPROPER_LIMIT = 9004
IMPROPER_SORTBY =  9004
IMPROPER_SORTBY_CODE = 9001
IMPROPER_TIME= 9004
ERROR_CODE_PERMISSION_DENIED = 9008
FILE_DOES_NOT_EXIST= 'file does not exist'
ADOM_LIST_EMPTY = 'adom list empty'
UNIT_TEST_TOP_POLICY_HITS = 'top-policy-hits'
HOST_NOT_REACHABLE = 'Host Not Reachable'
FORTINET_ANALYZER_NOT_REACHABLE = 'Fortinet Analyzer is not reachable'
SORT_BY_NOT_SUPPORTED = "Sort by is not supported"
FILTER_NOT_SUPPORTED = "Filter is not supported"
FORTINET_MANAGER_NOT_REACHABLE = 'Fortinet Manager is not reachable'
EXPECTED_HOSTRESPONDEDWITHERROR_EXCEPTION = 'HostRespondedWithError'
BAD_ADOM_NAME ='Yasen_LAB'
ERROR_CODE_AUTHERIZATION_ERROR=9000
INTERNAL_SERVER_ERROR=9000
BAD_ADOM_NAME_RESPONSE_CODE=9007
FILE_DOES_NOT_EXIST='file does not exist'
ADOM_LIST_EMPTY ='adom list empty'
EXPECTED_TOKENCREATION_EXCEPTION = "TokenCreationException"
EXPECTED_INVALID_MATRIC_NAME="Invalid metric name"
UNIT_TEST_BANDWIDTH_SUMMARY = "bandwidth-summary"
# --------- Unit Test Constants ENDS HERE --------
